import os
import fitz
from docx import Document
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

OUTPUT_DIR = os.path.join(os.path.expanduser("~"), "JarvisFiles")
os.makedirs(OUTPUT_DIR, exist_ok=True)

def get_output_path(filename: str) -> str:
    return os.path.join(OUTPUT_DIR, filename)

def save_text_file(content: str, filename: str = None) -> str:
    filename = filename or f"jarvis_note_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    path = get_output_path(filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path

def save_markdown(content: str, filename: str = None) -> str:
    filename = filename or f"jarvis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path = get_output_path(filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path

def save_docx(content: str, title: str = "Jarvis Report", filename: str = None) -> str:
    filename = filename or f"jarvis_doc_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    path = get_output_path(filename)
    doc = Document()
    doc.add_heading(title, 0)
    doc.add_paragraph(f"Generated by Jarvis — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    doc.add_paragraph("")
    for line in content.split("\n"):
        if line.startswith("# "):
            doc.add_heading(line[2:], level=1)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.strip():
            doc.add_paragraph(line)
    doc.save(path)
    return path

def save_pdf(content: str, title: str = "Jarvis Report", filename: str = None) -> str:
    filename = filename or f"jarvis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    path = get_output_path(filename)
    doc = SimpleDocTemplate(path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 24))
    for line in content.split("\n"):
        if line.strip():
            story.append(Paragraph(line, styles["Normal"]))
            story.append(Spacer(1, 6))
    doc.build(story)
    return path

def annotate_pdf(input_bytes: bytes, annotations: str, filename: str = None) -> str:
    filename = filename or f"jarvis_annotated_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    path = get_output_path(filename)
    with fitz.open(stream=input_bytes, filetype="pdf") as doc:
        for page in doc:
            # Add a highlight annotation with Jarvis summary on first page
            if page.number == 0:
                rect = fitz.Rect(50, 50, 545, 100)
                annot = page.add_rect_annot(rect)
                annot.set_colors(stroke=(0, 0.8, 1), fill=(0, 0.8, 1, 0.1))
                annot.set_info(content=annotations[:500])
                annot.update()
        doc.save(path)
    return path